# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-deepview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build deepview
        run: |
          python -m pip install build
          cd src/deepview
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: deepview-dist
          path: src/deepview/dist/

  build-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build deepview_data
        run: |
          python -m pip install build
          cd src/deepview_data
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: deepview-data-dist
          path: src/deepview_data/dist/

  build-tensorflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build deepview_tensorflow
        run: |
          python -m pip install build
          cd src/deepview_tensorflow
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: deepview-tensorflow-dist
          path: src/deepview_tensorflow/dist/

  build-torch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build deepview_torch
        run: |
          python -m pip install build
          cd src/deepview_torch
          python -m build
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: deepview-torch-dist
          path: src/deepview_torch/dist/

  publish-deepview:
    runs-on: ubuntu-latest
    needs: build-deepview
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/deepview
    steps:
      - name: Retrieve distributions
        uses: actions/download-artifact@v4
        with:
          name: deepview-dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  publish-data:
    runs-on: ubuntu-latest
    needs: build-data
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/deepview-data
    steps:
      - name: Retrieve distributions
        uses: actions/download-artifact@v4
        with:
          name: deepview-data-dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  publish-tensorflow:
    runs-on: ubuntu-latest
    needs: build-tensorflow
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/deepview-tensorflow
    steps:
      - name: Retrieve distributions
        uses: actions/download-artifact@v4
        with:
          name: deepview-tensorflow-dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

  publish-torch:
    runs-on: ubuntu-latest
    needs: build-torch
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/deepview-torch
    steps:
      - name: Retrieve distributions
        uses: actions/download-artifact@v4
        with:
          name: deepview-torch-dist
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
